version: '3.8'

networks:
  prime-it-laravel-network:
    driver: bridge
    external: true

services:
  mariadb-prim-it:
    image: bitnami/mariadb:10.6.19
    container_name: mariadb-prim-it
    networks:
      - prime-it-laravel-network
    volumes:
      - ./db:/bitnami/mariadb
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_USER: db_prime_it_user
      MARIADB_DATABASE: prime_it_db
    ports:
      - "3307:3306"

  phpmyadmin-prim-it:
    image: phpmyadmin
    networks:
      - prime-it-laravel-network
    ports:
      - "8083:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=512M

  mailhog-prim-it:
    image: mailhog/mailhog
    container_name: mailhog-prim-it
    networks:
      - prime-it-laravel-network
    ports:
      - "1026:1025"
      - "8026:8025"

  laravel-prim-it:
    image: bitnami/laravel:11.0.9
    networks:
      - prime-it-laravel-network
    ports:
      - "8082:8082"
      - "5175:5175"
    volumes:
      - ./src:/app
    environment:
      VITE_PORT: 5175
      VITE_HOST: "0.0.0.0"
      PHP_MEMORY_LIMIT: 1024M
      PHP_MAX_EXECUTION_TIME: 3600
      DB_HOST: mariadb-prim-it
      DB_PORT: 3306
      DB_USERNAME: root
      DB_DATABASE: prime_it_db
    working_dir: /app
    command: >
      bash -c "
        composer install &&
        php artisan serve --host=0.0.0.0 --port=8082 &
        npm install &&
        npm run dev
      "

  # ─────────────────────────────
  # JENKINS (added below)
  # ─────────────────────────────
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root                       # so Jenkins can access the Docker socket
    networks:
      - prime-it-laravel-network
    ports:
      - "8080:8080"                  # Jenkins UI
      - "50000:50000"                # JNLP agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_home/init.groovy.d:/var/jenkins_home/init.groovy.d
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

volumes:
  jenkins_home: