name: Build, test and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Create database
        run: touch database/database.sqlite
        working-directory: src

      - name: Copy .env
        run: cp .env.test .env
        working-directory: src

      - name: Install app
        run: composer install
        working-directory: src

      - name: Run migrations
        run: php artisan migrate
        working-directory: src

      - name: Run seeders
        run: php artisan db:seed
        working-directory: src

      - name: Run Unit Test & Feature Test
        run: ./vendor/bin/phpunit
        working-directory: src

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.APP_PATH }}

            rm -f build.sh

            cat > build.sh << 'EOF'
#!/bin/bash

  set -e
  
  echo "🚀 Running deploy script"
  
  echo "[1/5] Pulling from GitHub"
  git fetch origin
  git reset --hard origin/main
  
  echo "[2/5] Creating database if one isn't found"
  mkdir -p database
  touch database/database.sqlite
  
  echo "[3/5] Installing packages using composer"
  composer install --no-interaction --prefer-dist --optimize-autoloader
  
  echo "[4/5] Generating app key"
  php artisan key:generate
  
  echo "[5/5] Migrating and seeding database"
  php artisan migrate --force
  php artisan db:seed --force
  
  echo "✅ The app has been built and deployed!"
  EOF
  
  chmod +x build.sh
  ./build.sh