name: Build, test and deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Create database
        run: touch database/database.sqlite
        working-directory: src

      - name: Copy .env
        run: cp .env.test .env
        working-directory: src

      - name: Install app
        run: composer install
        working-directory: src

      - name: Run migrations
        run: php artisan migrate
        working-directory: src

      #- name: Test PHPStan
      #  run: ./vendor/bin/phpstan analyse --memory-limit=-1
      #  working-directory: src

      - name: Run Unit Test & Feature Test
        run: ./vendor/bin/phpunit
        working-directory: src

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
                  cd ${{ secrets.APP_PATH }}
                  echo "#!/bin/bash" > build.sh
                  echo "" >> build.sh
                  echo "echo \"Running deploy script\"" >> build.sh
                  echo "" >> build.sh
                  echo "echo \"[1/5] Pulling from GitHub\"" >> build.sh
                  echo "git pull origin" >> build.sh
                  echo "" >> build.sh
                  echo "echo \"[2/5] Creating database if one isn't found\"" >> build.sh
                  echo "touch database/database.sqlite" >> build.sh
                  echo "" >> build.sh
                  echo "echo \"[3/5] Installing packages using composer\"" >> build.sh
                  echo "composer install" >> build.sh
                  echo "" >> build.sh
                  echo "echo \"[4/5] Publishing API Platform assets\"" >> build.sh
                  echo "php artisan api-platform:install" >> build.sh
                  echo "" >> build.sh
                  echo "echo \"[5/5] Migrating database\"" >> build.sh
                  echo "php artisan migrate --force" >> build.sh
                  echo "" >> build.sh
                  echo "echo \"The app has been built and deployed!\"" >> build.sh
                  
                  # Make the script executable
                  chmod +x build.sh
            
                  # Run the script
                  ./build.sh
